module.exports = {
  ACTION_TYPE: {
    ADD_LEARNING_ACTION: 'ADD_LEARNING_ACTION',
    ADD_GROUP_ACTION: 'ADD_GROUP_ACTION',
    MARK_COMPLETE: 'MARK_COMPLETE',
    MARK_INCOMPLETE: 'MARK_INCOMPLETE',
    REMOVE_GROUP_ACTION: 'REMOVE_GROUP_ACTION',
    REMOVE_LEARNING_ACTION: 'REMOVE_LEARNING_ACTION',
    MOVE_LEARNING_ACTION: 'MOVE_LEARNING_ACTION',
    RENAME_GROUP_ACTION: 'RENAME_GROUP_ACTION',
    RENAME_LEARNING_ACTION: 'RENAME_LEARNING_ACTION'
  }
}
